export const switchesInitialState = {
  model: "",
  title: "",
  description: "",
  type: "switches",
  pdfUrl: "",
  dfxUrl: "",
  s2pUrl: "",
  buyNowUrl: "",
  featureProduct: false,
  insertionLoss: "",
  returnLoss: "",
  status: "",
  frequencyRange: "",
  switchTopology: "",
  averagePower: "",
  peakPower: "",
  iso: "",
  ip3: "",
  imageUrl:
    "https://res.cloudinary.com/daiaiwq1q/image/upload/c_scale,w_774/v1622480962/News/RFuWLogo_qqly5e.png",
  publicId: "News/RFuWLogo_qqly5e.png"
};
export const limitersubutialState = {
  model: "",
  title: "",
  description: "",
  type: "limiters",
  pdfUrl: "",
  dfxUrl: "",
  s2pUrl: "",
  buyNowUrl: "",
  featureProduct: false,
  insertionLoss: "",
  returnLoss: "",
  status: "",
  limiterDescription: "",
  frequency: "",
  inputPowerCw: "",
  inputPowerPeak: "",
  flatLeakage: "",
  spikeLeakage: "",
  recoveryTime: "",
  imageUrl:
    "https://res.cloudinary.com/daiaiwq1q/image/upload/c_scale,w_774/v1622480962/News/RFuWLogo_qqly5e.png",
  publicId: "News/RFuWLogo_qqly5e.png"
};
export const swDriversInitialState = {
  model: "",
  title: "",
  description: "",
  type: "swdrivers",
  pdfUrl: "",
  dfxUrl: "",
  s2pUrl: "",
  buyNowUrl: "",
  featureProduct: false,
  content: "",
  control: "",
  voltage1: "",
  voltage2: "",
  sinkMa: "",
  sourceMa: "",
  imageUrl:
    "https://res.cloudinary.com/daiaiwq1q/image/upload/c_scale,w_774/v1622480962/News/RFuWLogo_qqly5e.png",
  publicId: "News/RFuWLogo_qqly5e.png"
};
export const coLimitersInitialState = {
  model: "",
  title: "",
  description: "",
  type: "colimiters",
  pdfUrl: "",
  dfxUrl: "",
  s2pUrl: "",
  buyNowUrl: "",
  featureProduct: false,
  insertionLoss: "",
  returnLoss: "",
  status: "",
  limiterDescription: "",
  frequency: "",
  inputPowerCw: "",
  inputPowerPeak: "",
  flatLeakage: "",
  spikeLeakage: "",
  recoveryTime: "",
  imageUrl:
    "https://res.cloudinary.com/daiaiwq1q/image/upload/c_scale,w_774/v1622480962/News/RFuWLogo_qqly5e.png",
  publicId: "News/RFuWLogo_qqly5e.png"
};
